### ISSUE TITLE
About Keycloakify v2

### ISSUE THREAD

**Issue by garronej** [3tav/MojECE.IdentityTheme#2]
Hey @markodvornik very exiting to see what we did InseeFrLab reimplemented by you guys. We ❤️ it!  
Have you checkout [keycloakify v2](https://github.com/InseeFrLab/keycloakify) though.  
It's a big improvement from v1.  
There is:
- Better debugging experience with the ability to easily overwrite the default mock values. 
- Support for Keycloak plugins that introduce non standard ftl values. 
  (Like for example [this plugin](https://github.com/micedre/keycloak-mail-whitelisting) that define `authorizedMailDomains` in `register.ftl`). 
- You can implement custom `.ftl` pages that are not here by default.

You can check an example setup [here](https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel)

**Comment by markodvornik** [comment]
Hi, thanx for the update. I've just seen the update to v2 and will definetly try it. Thanks for all the work so far.
